---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dta-admin-ingress
  annotations:
    #nginx.ingress.kubernetes.io/enable-cors: "true"
    kubernetes.io/ingress.class: "nginx"
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - "{{ .Values.ingress.hostDta }}"
    secretName: admin-tls-secret # < cert-manager will store the created certificate in this secret.
  rules:
  - host: "{{ .Values.ingress.hostDta }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dta-admin-svc
            port:
              number: 80