---
apiVersion: v1
kind: Service
metadata:
  name: dta-admin-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: dta-admin
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP