const SET_USER = 'SET_USER';
const CLEAR_USER = 'CLEAR_USER';

const SET_SCENES = 'SET_SCENES';
const SET_ACTIVE_SCENE = 'SET_ACTIVE_SCENE';
const SET_GROUPS = 'SET_GROUPS';
const SET_CHANGED_SCENE = 'SET_CHANGED_SCENE';
const ADD_NEW_SCENE = 'ADD_NEW_SCENE';
const ADD_TAKE = 'ADD_TAKE';
const SET_TAKES = 'SET_TAKES';
const CLEAR_SCENES = 'CLEAR_SCENES';

const SET_USERS_INTERFACE = 'SET_USERS_INTERFACE';
const SET_SCENES_INTERFACE = 'SET_SCENES_INTERFACE';

const SET_USERS_LIST = 'SET_USERS_LIST';
const SET_ACTIVE_USER = 'SET_ACTIVE_USER';
const SET_CHANGED_USER = 'SET_CHANGED_USER';
const ADD_NEW_USER = 'ADD_NEW_USER';

const SET_ERROR = 'SET_ERROR';
const SET_LOADER = 'SET_LOADER';
const SET_SUCCESS = 'SET_SUCCESS';

export {
    SET_USER,
    CLEAR_USER,

    SET_SCENES,
    SET_ACTIVE_SCENE,
    SET_GROUPS,
    SET_CHANGED_SCENE,
    ADD_NEW_SCENE,
    ADD_TAKE,
    SET_TAKES,
    CLEAR_SCENES,

    SET_USERS_INTERFACE,
    SET_SCENES_INTERFACE,

    SET_USERS_LIST,
    SET_ACTIVE_USER,
    SET_CHANGED_USER,
    ADD_NEW_USER,

    SET_ERROR,
    SET_LOADER,
    SET_SUCCESS
}