// Profile
const SET_WATCHER = 'SET_WATCHER';
const SET_SPEAKER = 'SET_SPEAKER';
const SET_WAITER = 'SET_WAITER';
const SET_USER = 'SET_USER';
const SET_DEFAULT_PROFILE = 'SET_DEFAULT_PROFILE';

// Socket
const START_SESSION = 'START_SESSION';
const DETERMINATE_SESSION = 'DETERMINATE_SESSION';
const SET_SESSION_HASH = 'SET_SESSION_HASH';
const CONNECT_SESSION = 'CONNECT_SESSION';
const SEND_VOICE_URL = 'SEND_VOICE_URL';
const SET_SESSION_STATUS = 'SET_SESSION_STATUS';
const SET_SESSION = 'SET_SESSION';
const SET_SESSION_DATA = 'SET_SESSION_DATA';
const SEND_SESSION_DATA = 'SEND_SESSION_DATA';
const SET_BLOB = 'SET_BLOB';
const SET_VOICE = 'SET_VOICE';
const WRONG_SESSION = 'WRONG_SESSION';
const SET_DEFAULT_SOCKET = 'SET_DEFAULT_SOCKET';
const SET_SCENE_AWAITING = 'SET_SCENE_AWAITING';
const TRY_TO_CHANGE_SPEAKER = 'TRY_TO_CHANGE_SPEAKER';
const CHANGE_SPEAKER = 'CHANGE_SPEAKER';
const SET_CHANGE_REQUEST = 'SET_CHANGE_REQUEST';

// Scenes
const SET_SCENES = 'SET_SCENES';
const SET_ACTIVE_SCENE = 'SET_ACTIVE_SCENE';
const SET_DEFAULT_SCENES = 'SET_DEFAULT_SCENES';

// Controls
const SET_DEFAULT_VIDEO_STATUS = 'SET_DEFAULT_VIDEO_STATUS';
const SET_RECORDING_VOICE_STATUS = 'SET_RECORDING_VOICE_STATUS';
const SET_RECORDED_VIDEO_STATUS = 'SET_RECORDED_VIDEO_STATUS';
const SET_DEFAULT_VIDEO_DISABLE = 'SET_DEFAULT_VIDEO_DISABLE';
const SET_RECORDING_VOICE_DISABLE = 'SET_RECORDING_VOICE_DISABLE';
const SET_RECORDED_VIDEO_DISABLE = 'SET_RECORDED_VIDEO_DISABLE';

export {
    // Profile
    SET_WATCHER,
    SET_SPEAKER,
    SET_WAITER,
    SET_USER,
    SET_DEFAULT_PROFILE,

    // Socket
    START_SESSION,
    DETERMINATE_SESSION,
    SET_SESSION_HASH,
    CONNECT_SESSION,
    SEND_VOICE_URL,
    SET_SESSION_STATUS,
    SET_SESSION,
    SET_SESSION_DATA,
    SEND_SESSION_DATA,
    SET_BLOB,
    SET_VOICE,
    WRONG_SESSION,
    SET_SCENE_AWAITING,
    SET_DEFAULT_SOCKET,
    TRY_TO_CHANGE_SPEAKER,
    CHANGE_SPEAKER,
    SET_CHANGE_REQUEST,

    // Scenes
    SET_SCENES,
    SET_ACTIVE_SCENE,
    SET_DEFAULT_SCENES,

    // Controls
    SET_DEFAULT_VIDEO_STATUS,
    SET_RECORDING_VOICE_STATUS,
    SET_RECORDED_VIDEO_STATUS,
    SET_DEFAULT_VIDEO_DISABLE,
    SET_RECORDING_VOICE_DISABLE,
    SET_RECORDED_VIDEO_DISABLE
}